version: "3"

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -template  ./.docker/app/nginx.conf:./.docker/nginx/nginx.conf -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - NGINX_PORT=9000
      - NGINX_HOST=app
      - NGINX_LISTEN=80
    volumes:
      - ./:/var/www/
    networks:
      - app-network
    depends_on:
      - db
      - redis

  db:
    build: .docker/mysql
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network
    volumes:
      - ./.docker/dbdata:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
